name: Convert to square dot image

on:
  push:
    paths:
      - 'a.spaces'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install pillow

      - run: python convert_square.py

      - uses: actions/upload-artifact@v4
        with:
          name: square-image
          path: a.png